In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
df=pd.read_csv('mushrooms.csv')
df

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [3]:
df.columns

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

In [4]:
df.isna().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [5]:
df.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
count          8124      8124       8124  ...                     8124   
unique            2         2         12  ...                        4   
top               c         b          b  ...                        s   
freq           6812      5612       1728  ...                     4936   

       stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

In [6]:
#Class column is response and rest columns are predictors.

X=df.drop('class',axis=1) #Predictors
y=df['class'] #Response
X.head()

cap-shape cap-surface cap-color bruises odor gill-attachment gill-spacing  \
0         x           s         n       t    p               f            c   
1         x           s         y       t    a               f            c   
2         b           s         w       t    l               f            c   
3         x           y         w       t    p               f            c   
4         x           s         g       f    n               f            w   

  gill-size gill-color stalk-shape  ... stalk-surface-below-ring  \
0         n          k           e  ...                        s   
1         b          k           e  ...                        s   
2         b          n           e  ...                        s   
3         n          n           e  ...                        s   
4         b          k           t  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 22 columns]

# Label encoding

In [7]:
from sklearn.preprocessing import LabelEncoder
Encoder_X = LabelEncoder() 
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
Encoder_y=LabelEncoder()
y = Encoder_y.fit_transform(y)

In [8]:
X.head()

cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0          5            2          4        1     6                1   
1          5            2          9        1     0                1   
2          0            2          8        1     3                1   
3          5            3          8        1     6                1   
4          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  stalk-shape  ...  \
0             0          1           4            0  ...   
1             0          0           4            0  ...   
2             0          0           5            0  ...   
3             0          1           5            0  ...   
4             1          0           4            1  ...   

   stalk-surface-below-ring  stalk-color-above-ring  stalk-color-below-ring  \
0                         2                       7                       7   
1                         2                       7                       7   
2                         2                       7                       7   
3                         2                       7                       7   
4                         2                       7                       7   

   veil-type  veil-color  ring-number  ring-type  spore-print-color  \
0          0           2            1          4                  2   
1          0           2            1          4                  3   
2          0           2            1          4                  3   
3          0           2            1          4                  2   
4          0           2            1          0                  3   

   population  habitat  
0           3        5  
1           2        1  
2           2        3  
3           3        5  
4           0        1  

[5 rows x 22 columns]

In [9]:
y

array([1, 0, 0, ..., 0, 1, 0])

Poisonous = 1
Eatable = 0

# Getting dummy variables

In [10]:
X=pd.get_dummies(X,columns=X.columns,drop_first=True)
X.head()

cap-shape_1  cap-shape_2  cap-shape_3  cap-shape_4  cap-shape_5  \
0            0            0            0            0            1   
1            0            0            0            0            1   
2            0            0            0            0            0   
3            0            0            0            0            1   
4            0            0            0            0            1   

   cap-surface_1  cap-surface_2  cap-surface_3  cap-color_1  cap-color_2  ...  \
0              0              1              0            0            0  ...   
1              0              1              0            0            0  ...   
2              0              1              0            0            0  ...   
3              0              0              1            0            0  ...   
4              0              1              0            0            0  ...   

   population_2  population_3  population_4  population_5  habitat_1  \
0             0             1             0             0          0   
1             1             0             0             0          1   
2             1             0             0             0          0   
3             0             1             0             0          0   
4             0             0             0             0          1   

   habitat_2  habitat_3  habitat_4  habitat_5  habitat_6  
0          0          0          0          1          0  
1          0          0          0          0          0  
2          0          1          0          0          0  
3          0          0          0          1          0  
4          0          0          0          0          0  

[5 rows x 95 columns]

# Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [12]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
X_train

array([[-0.02297586, -0.79088576, -0.34729656, ..., -0.40198689,
         4.72263472, -0.161767  ],
       [-0.02297586, -0.79088576, -0.34729656, ..., -0.40198689,
        -0.21174621, -0.161767  ],
       [-0.02297586, -0.79088576, -0.34729656, ..., -0.40198689,
        -0.21174621, -0.161767  ],
       ...,
       [-0.02297586,  1.26440511, -0.34729656, ...,  2.48764329,
        -0.21174621, -0.161767  ],
       [-0.02297586, -0.79088576,  2.87938356, ...,  2.48764329,
        -0.21174621, -0.161767  ],
       [-0.02297586, -0.79088576,  2.87938356, ..., -0.40198689,
        -0.21174621, -0.161767  ]])

In [14]:
# Applying Gaussian Naive Bayes Classifier

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score, precision_score,recall_score, f1_score
Classifier= GaussianNB()
Classifier.fit(X_train, y_train)
y_pred= Classifier.predict(X_test)
y_train_pred= Classifier.predict(X_train)

print("Training Accuracy is : ", accuracy_score(y_train, y_train_pred))
print('Accuracy Score is:', accuracy_score(y_test, y_pred))
print('Recall Score is:', recall_score(y_test, y_pred))
print('Precision Score:', precision_score(y_test, y_pred))
print('F1 score is:', f1_score(y_test, y_pred))
print("\n The confusion matrix is : \n", confusion_matrix(y_test, y_pred))

Training Accuracy is :  0.9511079845233907
Accuracy Score is: 0.9479081214109926
Recall Score is: 0.9991532599491956
Precision Score: 0.9035222052067381
F1 score is: 0.9489344591877764

 The confusion matrix is : 
 [[1131  126]
 [   1 1180]]


In [15]:
 # Applying Bernoulli Naive Bayes Classifier
    
from sklearn.naive_bayes import BernoulliNB
classifier= BernoulliNB()
classifier.fit(X_train, y_train)
y_pred1= classifier.predict(X_test)
y_train_pred1= classifier.predict(X_train)

print("Training Accuracy is : ", accuracy_score(y_train, y_train_pred1))
print('Accuracy Score is:', accuracy_score(y_test, y_pred1))
print('Recall Score is:', recall_score(y_test, y_pred1))
print('Precision Score:', precision_score(y_test, y_pred1))
print('F1 score is:', f1_score(y_test, y_pred1))
print("\n The confusion matrix is : \n", confusion_matrix(y_test, y_pred1))

Training Accuracy is :  0.9417868448821667
Accuracy Score is: 0.9339622641509434
Recall Score is: 0.8712955122777307
Precision Score: 0.9913294797687862
F1 score is: 0.9274447949526814

 The confusion matrix is : 
 [[1248    9]
 [ 152 1029]]


In [16]:
# Applying Decision Tree Classifier

from sklearn.tree import DecisionTreeClassifier
dt= DecisionTreeClassifier()
dt.fit(X_train,y_train)
y_pred2= dt.predict(X_test)

y_train_pred2 = dt.predict(X_train)

print("Training Accuracy is : ", accuracy_score(y_train, y_train_pred2))
print('Accuracy Score is:', accuracy_score(y_test, y_pred2))
print('Recall Score is:', recall_score(y_test, y_pred2))
print('Precision Score:', precision_score(y_test, y_pred2))
print('F1 score is:', f1_score(y_test, y_pred2))
print("\n The confusion matrix is : \n", confusion_matrix(y_test, y_pred2))

Training Accuracy is :  1.0
Accuracy Score is: 1.0
Recall Score is: 1.0
Precision Score: 1.0
F1 score is: 1.0

 The confusion matrix is : 
 [[1257    0]
 [   0 1181]]


In [17]:
# Applying Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier()
rf_model.fit(X_train,y_train)
y_pred3= rf_model.predict(X_test)

y_train_pred3= rf_model.predict(X_train)

print("Training Accuracy is : ", accuracy_score(y_train, y_train_pred3))
print('Accuracy Score is:', accuracy_score(y_test, y_pred3))
print('Recall Score is:', recall_score(y_test, y_pred3))
print('Precision Score:', precision_score(y_test, y_pred3))
print('F1 score is:', f1_score(y_test, y_pred3))
print("\n The confusion matrix is : \n", confusion_matrix(y_test, y_pred3))

Training Accuracy is :  1.0
Accuracy Score is: 1.0
Recall Score is: 1.0
Precision Score: 1.0
F1 score is: 1.0

 The confusion matrix is : 
 [[1257    0]
 [   0 1181]]


In [18]:
# Applying SVM Model
from sklearn import svm
from sklearn.svm import SVC

svm_linear = SVC(kernel= "linear")
svm_linear.fit(X_train,y_train)
y_pred4 = svm_linear.predict(X_test)

y_train_pred4 = svm_linear.predict(X_train)

print("Training Accuracy is : ", accuracy_score(y_train, y_train_pred4))
print('Accuracy Score is:', accuracy_score(y_test, y_pred4))
print('Recall Score is:', recall_score(y_test, y_pred4))
print('Precision Score:', precision_score(y_test, y_pred4))
print('F1 score is:', f1_score(y_test, y_pred4))
print("\n The confusion matrix is : \n", confusion_matrix(y_test, y_pred4))

Training Accuracy is :  1.0
Accuracy Score is: 1.0
Recall Score is: 1.0
Precision Score: 1.0
F1 score is: 1.0

 The confusion matrix is : 
 [[1257    0]
 [   0 1181]]


In [19]:
# Applying KNN model

from sklearn.neighbors import KNeighborsClassifier
classifer = KNeighborsClassifier(n_neighbors=4,metric = "minkowski") 
classifer.fit(X_train,y_train)
y_pred5 = classifer.predict(X_test)

y_train_pred5 = classifer.predict(X_train)

print("Training Accuracy is : ", accuracy_score(y_train, y_train_pred5))
print('Accuracy Score is:', accuracy_score(y_test, y_pred5))
print('Recall Score is:', recall_score(y_test, y_pred5))
print('Precision Score:', precision_score(y_test, y_pred5))
print('F1 score is:', f1_score(y_test, y_pred5))
print("\n The confusion matrix is : \n", confusion_matrix(y_test, y_pred5))

Training Accuracy is :  0.9996482588814632
Accuracy Score is: 0.9995898277276456
Recall Score is: 0.9991532599491956
Precision Score: 1.0
F1 score is: 0.9995764506565015

 The confusion matrix is : 
 [[1257    0]
 [   1 1180]]


In [20]:
# Applying Logistic Regression

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix,precision_score
log_model= LogisticRegression()
log_model.fit(X_train,y_train)
y_pred6 = log_model.predict(X_test)

y_train_pred6= log_model.predict(X_train)

print("Training Accuracy is : ", accuracy_score(y_train, y_train_pred6))
print('Accuracy Score is:', accuracy_score(y_test, y_pred6))
print('Recall Score is:', recall_score(y_test, y_pred6))
print('Precision Score:', precision_score(y_test, y_pred6))
print('F1 score is:', f1_score(y_test, y_pred6))
print("\n The confusion matrix is : \n", confusion_matrix(y_test, y_pred6))

Training Accuracy is :  1.0
Accuracy Score is: 1.0
Recall Score is: 1.0
Precision Score: 1.0
F1 score is: 1.0

 The confusion matrix is : 
 [[1257    0]
 [   0 1181]]


Decision Tree Classifier,Random Forest Classifier,SVM ANDLogistic Regression model gives the best scores in terms of accuracy score, precision score and F1 score